'patch article votes completed with error checks'
WelshSquirrel/BE-NEWS-NC pull request #4
Opened 2022-09-05 15:14 UTC by WelshSquirrel

2022-09-05 15:31 UTC, popatre requested changes
Just needs a few more tests

2022-09-05 15:31 UTC, popatre commented on __tests__/app.test.js
> +})
Some missing tests to add:

- [ ] 400 invalid id
- [ ]  200/400 inc_vote key missing - either respond with an error or make no change.

2022-09-06 09:42 UTC, WelshSquirrel commented
I have commented out a section of tests that crossed over from my next branch.

2022-09-06 09:47 UTC, popatre approved these changes

2022-09-06 09:47 UTC, popatre commented on __tests__/app.test.js
> +// describe('GET /api/articles/:article_id', () => {
Ideally these shouldn't even exist on this branch, as this branch is for a different feature. 

I'd make sure you're branching from main each time, then all the branches are independent, and all feed into main

2022-09-06 09:47 UTC, popatre commented on models/models.js
> +    return db.query('SELECT * FROM articles LEFT JOIN comments ON comments.article_id = articles.article_id WHERE article_id = $1;', [id])
I presume this is the next ticket, so should be it's own branch.

2022-09-06 09:51 UTC, merged